version: '3'

services:
  omnikdatalogger:
    build: .
    image: jbouwh/omnikdataloggerproxy:latest
    volumes:
      - "${PWD}/config.yaml:/config.yaml"
    expose:
      - "10004"
    logging:
      driver: json-file
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
